### ISSUE TITLE
The default destination items not loading

### ISSUE THREAD

**Issue by robsonflorentino** [czeckd/basic-dual-listbox-demo#1]
I just inverted the arrays thinking in load the destinations by default, but this don't work. What the wrong I did?

This is my html source:

<div class="container">
	<dual-list [source]="source" [(destination)]="target" height="150px"></dual-list>
</div>

This is my component source:

import { Component } from '@angular/core';

@Component({
	selector: 'app-root',
	templateUrl: './app.component.html'
})
export class AppComponent {
	source = [ ];
	target = [ 'Pawn', 'Rook', 'Knight', 'Bishop', 'Queen', 'King' ];
}

**Comment by czeckd** [comment]
The source is a superset of all available options.

So if you want all the chess pieces to be loaded by default, change it to be:
```typescript
export class AppComponent {
    source = [ 'Pawn', 'Rook', 'Knight', 'Bishop', 'Queen', 'King' ];
    target = [ 'Pawn', 'Rook', 'Knight', 'Bishop', 'Queen', 'King' ];
}
```

The dual-list component manages its internal target array by confirming it is available in the source array at the time it is added to its target array.

**Comment by robsonflorentino** [comment]
Sorry for my English.
That's rigth, I fixed my source and now works fine.
Tks for help me.
